require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  Exclude:
    - bin/*
Layout/LineLength:
  Enabled: true
  Max: 120

Style/Documentation:
  Enabled: false